Weights:
  Pi3X: './weights/pi3x.safetensors'
  Pi3: './weights/pi3.safetensors'
  DBoW: './weights/ORBvoc.txt'
  SALAD: './weights/dino_salad.ckpt'
  DNIO: './weights/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 120
  overlap: 60
  loop_chunk_size: 20 # imgs of loop chunk = 2 * loop_chunk_size
  loop_enable: True
  useDBoW: False
  delete_temp_files: True
  temp_files_location: 'cpu_memory' # choose between 'disk' or 'cpu_memory'
  align_lib: 'torch' # choose among 'triton' (GPU), 'torch' (GPU), 'numba' (CPU) or 'numpy' (CPU)
  align_method: 'se3' # choose among 'sim3', 'se3' or 'scale+se3'
  model_type: 'Pi3X' # choose between 'Pi3' and 'Pi3X'
  image_width: -1 # image_hight will be scaled to image_width, if set to None means PIXEL_LIMIT=255000. See `./pi3/utils/basic.py` line 11 function `load_images_as_tensor_pi_long(...)`
  
  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75 # conf_threshold = np.mean(confs) * conf_threshold_coef

Loop:
  DBoW:
    thresh: 0.034
    num_repeat: 3
    NMS: 25

  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.85 # 0.7 -> 0.85 for more accurate  detection
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'cpp' 
    # choose between 'cpp' or 'python'. will auto set 'python' if c++ version has not installed
    max_iterations: 30
    lambda_init: 1e-6